name-template: "v$NEXT_MINOR_VERSION 🌈"

tag-template: "v$NEXT_MINOR_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"

  - title: "🐛 Bug Fixes"
    labels:
      - "bug"

  - title: "🧰 Maintenance"
    label:
      - "maintenance"

  - title: "📄 Documentation"
    label:
      - "doc"

  - title: "🤖 dependabot"
    label:
      - "dependabot"

exclude-labels:
  - "skip:changelog"
  - "trivial"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## Changes

  $CHANGES
