name: CI
on:
  push:
    tags:
      - v*.*.*
    branches:
      - master
      - main
    paths:
      - "**.go"
      - ".goreleaser.yml"
      - ".golangci.yml"
      - ".dockerignore"
      - "Makefile"
      - "rules.mk"
      - "go.*"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**.go"
      - ".goreleaser.yml"
      - ".golangci.yml"
      - "Docker*"
      - ".dockerignore"
      - "Makefile"
      - "go.*"
      - ".github/workflows/go.yml"

jobs:
  tests-on-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        golang: [1.16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.golang }}
      - name: Run 'make ci' on Windows
        run: make.exe ci
        continue-on-error: true

  tests-on-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        golang: [1.16.x]
    env:
      OS: macos-latest
      GOLANG: ${{ matrix.golang }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.golang }}

      - uses: actions/cache@v3.0.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.golang }}-v1-

      - name: Run 'make ci' on MacOS
        run: make ci

      - name: Check go.mod and go.sum
        run: |
          go mod tidy -v
          git --no-pager diff go.mod go.sum
          git --no-pager diff --quiet go.mod go.sum

  tests-on-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: [1.16.x]
    env:
      OS: ubuntu-latest
      GOLANG: ${{ matrix.golang }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.golang }}

      - uses: actions/cache@v3.0.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.golang }}-v1-

      - name: Run 'make ci' on MacOS
        run: make ci

      - name: Check go.mod and go.sum
        run: |
          go mod tidy -v
          git --no-pager diff go.mod go.sum
          git --no-pager diff --quiet go.mod go.sum
