name: Docker

on:
  push:
    tags: ["v*.*.*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: BUILD_ARG_VERSION=${{ github.ref }}
          context: .
          push: true
          tags: |
            ghcr.io/yesino/line-coverange:latest
            ghcr.io/yesino/line-coverange:${{ github.ref }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
