name: Release Drafter

on:
  push:
    branches:
      - master
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          tag: "v$NEXT_MINOR_VERSION"
          version: "v$NEXT_MINOR_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
